### ISSUE TITLE
mjx-container - not handling centre 

### ISSUE THREAD

**Issue by theonlydaleking** [kognise/obsidian-atom#26]
Is there a reason [this rule](https://github.com/kognise/obsidian-atom/blob/f067667e7c70b420b3031fe2424536c259198b99/obsidian.css#L174) was included? My understanding of MathJax is that double $$ should centre the equation, and you use single $ for inline. This css rule overwrites this behaviour unfortunately.

**Comment by kognise** [comment]
This is a me-being-opinionated thing, probably one of several. I personally prefer double-$$ MathJax left-aligned over centered in my math/physics notes.

My instinct is not to "fix" this, although perhaps there's some technical reason for centering MathJax that I'm missing!

You can, if you wish, use a custom CSS snippet:

```css
mjx-container {
  text-align: center !important;
}
```

**Comment by theonlydaleking** [comment]
Yup thought that might be the case - completely understand. I added a custom rule myself like you suggested and all is well. 
Just thought I'd check to see if it was a mistake or on purpose
