### ISSUE TITLE
Please add lighter (less contrasty) options through style settings plugins

### ISSUE THREAD

**Issue by bbecausereasonss** [kognise/obsidian-atom#29]
Looking for more options for this theme, which I like. ie) lighter background options for the side bars... colored headers.

**Comment by kognise** [comment]
This theme is meant to be a bit opinionated — colored headers are awesome, but I don't personally want to include them in the CSS files I'm distributing. I highly encourage you to add on your own custom CSS, though!

See:

- [Obsidian Help: CSS snippets](https://help.obsidian.md/Extending+Obsidian/CSS+snippets)
- [Code example](https://forum.obsidian.md/t/help-changing-color-of-headers/1465/2)
