### ISSUE TITLE
Line spacing breaks when changing the font size.

### ISSUE THREAD

**Issue by kaiwizz** [kognise/obsidian-atom#7]
Hello,

Thanks a lot for this awesome theme. I like it a lot. But I am facing an issue. When I change the font size, the line spacing breaks and it gets all jumbled up. The issue is especially prominent in the header sections.

This is the editor view
![image](https://user-images.githubusercontent.com/17363383/119123708-a8150800-ba51-11eb-9110-c8826bfd4c3b.png)

And here is the preview
![image](https://user-images.githubusercontent.com/17363383/119123770-bc590500-ba51-11eb-935d-c5411cf48abe.png)

And this is what happens if I increase the fonts
![image](https://user-images.githubusercontent.com/17363383/119123880-de528780-ba51-11eb-8fd9-bd179297040d.png)

**Comment by kognise** [comment]
That's not good! I'll check it out.

**Comment by kaiwizz** [comment]
@kognise any update?

**Comment by kognise** [comment]
I'm reallllly sorry for the absurdly long wait, fixed by 4a6cd4ece4ea37493a068af95b6c592e8fcaaee6.
