### ISSUE TITLE
LaTeX in headers is rendered at the wrong size.

### ISSUE THREAD

**Issue by levymitchell0** [kognise/obsidian-atom#9]
This can be easily remedied by removing the `font-size: 20px;` line in the `mjx-container[jax='CHTML']` rule.

To see what I'm talking about, create a new note with:

`# Cool math: $\mathbb R^3$`

I would open a PR, but forking the entire repo to change a single line of code seems a bit overkill 😅. I've been using this change on my personal `Atom.css` and haven't noticed any formatting issues.

While we're at it, I'd suggest adding
```css
.math-block {
  font-size: 1.25em;
}
```
as this makes `$$` math blocks much easier to read.

Thanks for the super cool theme!

**Comment by kognise** [comment]
Thanks! Added your suggestions.

Side note, dear god the CSS file has gotten horrid as I've just added stuff over the time this has been a thing. I really have to reorganize everything and comment it.

**Comment by levymitchell0** [comment]
I feel that; keeping stuff like that up to date always gets me.

I don't know enough about the obsidian theme interface to be of *toooo* much help, but if you want someone who's unfamiliar with it to give it a once over to make sure it's understandable (I know my comments are sometimes... less than comprehensible) feel free to give me a ping from the PR!
